# Set up your minecraft java acc
bot:
  account:
    type: "microsoft"
    email: "your-email@gmail.com"
    password: "dein-microsoft-passwort"

  # Bot behavior
  behavior:
    auto-connect-on-startup: true
    auto-reconnect: true
    reconnect-delay-seconds: 30
    max-reconnect-attempts: 10
    idle-timeout-minutes: 60

  # Advanced
  advanced:
    keep-alive-interval: 20
    connection-timeout: 10
    packet-delay-ms: 50

# General settings
plugin:
  language: "en-us" # en-us, de-de
  debug-mode: true
  log-packets: true
